# syntax = docker/dockerfile:1.2
FROM node:latest

WORKDIR /back-end/back-end/

COPY . /back-end/back-end/

EXPOSE 4000

RUN --mount=type=secret,id=_env,dst=/etc/secrets/.env
RUN npm install

CMD ["npm", "run", "prod"]
